### ISSUE TITLE
AttributeError: 'int' object has no attribute 'keys'

### ISSUE THREAD

**Issue by EnkrateiaLucca** [tirthajyoti/UCI-ML-API#5]
Hi I tried to print all the datasets to see which I wanted to download but I got an issue with the print_all_datastes_names() functions, apparently the url for the uci dataset is returing server error and then here is giving an int instead of the dictionary. Is there a link to the UCI dataset that I can replace in the script?

Traceback (most recent call last):   File "Main.py", line 29, in <module>     execute_choice()   File "/home/lucassoares/Desktop/projects/tmp_files/UCI-ML-API/Choice.py", line 66, in execute_choice     print_all_datasets_names()   File "/home/lucassoares/Desktop/projects/tmp_files/UCI-ML-API/UCI_ML_Functions.py", line 426, in print_all_datasets_names     for key in dict1.keys():

**Comment by jens-38** [comment]
The solution I presented in https://github.com/tirthajyoti/UCI-ML-API/issues/4#issuecomment-790630839 applies here as well.
